networks:
  proxy:
    external: true

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:2025.4.0
    command: tunnel --no-autoupdate run
    networks:
      - proxy
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
