services:
  dozzle:
    container_name: dozzle
    image: docker.io/amir20/dozzle:v8.13.3
    ports:
      - 8888:8080
    environment:
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
