services:
  minecraft:
    container_name: minecraft
    image: docker.io/itzg/minecraft-server:2025.6.2
    ports:
      - 25565:25565 # java port
      - 19132:19132/udp # bedrock port
      - 25575:25575 # rcon port
    environment:
      TZ: ${TZ}
      EULA: true
      TYPE: PAPER
      SNOOPER_ENABLED: false
      RCON_PASSWORD: ${RCON_PASSWORD}
      VERSION: LATEST
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      SERVER_NAME: ARKON
      MOTD: Welcome to ARKON!
      SEED: ${SEED}
      ICON: https://github.com/kabankz.png
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/geyseroptionalpack/versions/latest/builds/latest/downloads/geyseroptionalpack
        https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.4.0/PAPER/ViaVersion-5.4.0.jar
    volumes:
      - ./data:/data:rw
    stdin_open: true
    tty: true
    restart: unless-stopped
