services:
  minecraft:
    container_name: minecraft
    image: docker.io/itzg/minecraft-server:2025.6.0
    ports:
      - 25565:25565 # java port
      - 19132:19132/udp # bedrock port
    environment:
      TZ: ${TZ}
      EULA: "true"
      TYPE: "PAPER"
      PAPER_CHANNEL: experimental
      SNOOPER_ENABLED: "false"
      VERSION: "LATEST"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "10"
      SERVER_NAME: "ARKON"
      MOTD: "Welcome to ARKON!"
      ICON: "https://github.com/kabankz.png"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    volumes:
      - ./data:/data:rw
    restart: unless-stopped
