#!/usr/bin/env bash

echo -n "Are you sure you want to reset the world? [y/N] "
read -r answer

if [[ ! $answer =~ ^[Yy]$ ]]; then
  echo "Operation cancelled"
  exit 1
fi

rm -rdf data/world data/world_nether data/world_the_end
echo "World reset"
