services:
  uptime-kuma:
    container_name: uptime-kuma
    image: docker.io/louislam/uptime-kuma:1.23.16
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
