services:
  dockge:
    container_name: dockge
    image: docker.io/louislam/dockge:1.5.0
    ports:
      - 5001:5001
    environment:
      - DOCKGE_STACKS_DIR=${HOME}/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${HOME}/docker:${HOME}/docker:rw
      - ./data:/app/data:rw
    restart: unless-stopped
